ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_REGISTERED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'USER_LOGGED_IN';

ALTER TABLE "audit_events" ALTER COLUMN "workspaceId" DROP NOT NULL;
